services:
  streamlit:
    build: .
    container_name: jobsetmatch-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    env_file:
      - app/.env
    command: streamlit run app.py --server.runOnSave=true
    environment:
      - PYTHONPATH=/app
